#!/bin/bash
# =============================================================================
# PiRacer Head Unit - Yocto 빌드 스크립트 (Docker/Ubuntu 22.04)
# 사용법:
#   ./docker-build.sh [TARGET]
#
# TARGET 예시:
#   piracer-hu-image        (기본값) Head Unit 이미지
#   piracer-cluster-image   Instrument Cluster 이미지
#   headunit                headunit 패키지만 빌드
#
# 환경 변수:
#   BB_NUMBER_THREADS   BitBake 병렬 스레드 수 (기본: 호스트 코어 수)
#   SKIP_DOCKER_BUILD   1로 설정하면 Docker 이미지 재빌드 생략
#   BITBAKE_EXTRA_ARGS  BitBake 추가 옵션 (예: -p 로 parse-only 검증)
# =============================================================================
set -e

# ── 경로 설정 ────────────────────────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(dirname "${SCRIPT_DIR}")"
BUILD_DIR="${SCRIPT_DIR}/build-rpi"
DOCKER_IMAGE="piracer-yocto-builder:ubuntu22"

TARGET="${1:-piracer-hu-image}"

is_xen_target() {
    case "${TARGET}" in
        piracer-dom0-image|xen-image-minimal|xen-guest-image-minimal|xen-rpi-u-boot-scr|xen|xen-tools)
            return 0
            ;;
        *)
            return 1
            ;;
    esac
}

# ── 색상 출력 ────────────────────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log_info()  { echo -e "${BLUE}[INFO]${NC}  $*"; }
log_ok()    { echo -e "${GREEN}[OK]${NC}    $*"; }
log_warn()  { echo -e "${YELLOW}[WARN]${NC}  $*"; }
log_error() { echo -e "${RED}[ERROR]${NC} $*"; }

# ── 사전 검사 ────────────────────────────────────────────────────────────────
echo "============================================================"
echo "  PiRacer Yocto Build  |  Target: ${TARGET}"
echo "============================================================"

# Docker 설치 확인
if ! command -v docker &>/dev/null; then
    log_error "Docker가 설치되어 있지 않습니다."
    exit 1
fi

# 디스크 공간 검사 (최소 80GB 필요)
AVAIL_GB=$(df -BG "${REPO_ROOT}" | awk 'NR==2{gsub(/G/,"",$4); print $4}')
if [ "${AVAIL_GB}" -lt 80 ]; then
    log_warn "디스크 여유 공간이 ${AVAIL_GB}GB입니다. Yocto 빌드는 ~100GB 필요합니다."
fi
log_info "사용 가능한 디스크: ${AVAIL_GB}GB"

for REQUIRED_DIR in poky meta-openembedded meta-raspberrypi meta-qt5 meta-piracer; do
    if [ ! -d "${SCRIPT_DIR}/${REQUIRED_DIR}" ]; then
        log_error "필수 Yocto layer가 없습니다: yocto/${REQUIRED_DIR}"
        log_error "submodule 또는 별도 clone으로 해당 layer를 먼저 준비하세요."
        exit 1
    fi
done

if is_xen_target; then
    if [ ! -d "${SCRIPT_DIR}/meta-openembedded/meta-filesystems" ]; then
        log_error "Xen 빌드에 필요한 layer가 없습니다: yocto/meta-openembedded/meta-filesystems"
        log_error "meta-openembedded 전체 layer collection을 준비하세요."
        exit 1
    fi

    if [ ! -d "${SCRIPT_DIR}/meta-virtualization" ]; then
        log_error "Xen 빌드에 필요한 layer가 없습니다: yocto/meta-virtualization"
        log_error "준비 명령: git clone -b scarthgap https://git.yoctoproject.org/meta-virtualization yocto/meta-virtualization"
        exit 1
    fi
fi

# ── Docker 이미지 빌드 ───────────────────────────────────────────────────────
if [ "${SKIP_DOCKER_BUILD}" != "1" ]; then
    log_info "Docker 이미지 빌드 중: ${DOCKER_IMAGE}"
    docker build \
        --build-arg UID="$(id -u)" \
        --build-arg GID="$(id -g)" \
        --build-arg USERNAME="yocto" \
        -t "${DOCKER_IMAGE}" \
        "${SCRIPT_DIR}"
    log_ok "Docker 이미지 준비 완료"
else
    log_info "Docker 이미지 빌드 생략 (SKIP_DOCKER_BUILD=1)"
fi

# ── BitBake 빌드 명령 ────────────────────────────────────────────────────────
MOUNT_TARGET="/workspace/xen-hypervisor"
EXTRA_BBLAYERS=""
ENABLE_XEN_CONFIG="0"

if is_xen_target; then
    EXTRA_BBLAYERS="  ${MOUNT_TARGET}/yocto/meta-openembedded/meta-filesystems \\
  ${MOUNT_TARGET}/yocto/meta-virtualization \\"
    ENABLE_XEN_CONFIG="1"
fi

log_info "Docker 컨테이너 내부에서 BitBake 실행"
log_info "  빌드 대상: ${TARGET}"
log_info "  마운트:    ${REPO_ROOT} → ${MOUNT_TARGET}"

docker run --rm \
    --name "piracer-yocto-build-$$" \
    -v "${REPO_ROOT}:${MOUNT_TARGET}" \
    -e HOME="/home/yocto" \
    -e USER="yocto" \
    -e BB_ENV_PASSTHROUGH_ADDITIONS="BB_NUMBER_THREADS PARALLEL_MAKE" \
    -e BB_NUMBER_THREADS="${BB_NUMBER_THREADS:-$(nproc)}" \
    -e PARALLEL_MAKE="-j${BB_NUMBER_THREADS:-$(nproc)}" \
    "${DOCKER_IMAGE}" \
    bash -c "
        set -e
        cd ${MOUNT_TARGET}/yocto

        echo '[Docker] oe-init-build-env 초기화 중...'
        source poky/oe-init-build-env build-rpi

        cat > conf/bblayers.conf <<EOF
# Generated by yocto/docker-build.sh
POKY_BBLAYERS_CONF_VERSION = \"2\"
BBPATH = \"\\\${TOPDIR}\"
BBFILES ?= \"\"
BBLAYERS ?= \" \\
  ${MOUNT_TARGET}/yocto/poky/meta \\
  ${MOUNT_TARGET}/yocto/poky/meta-poky \\
  ${MOUNT_TARGET}/yocto/poky/meta-yocto-bsp \\
  ${MOUNT_TARGET}/yocto/meta-openembedded/meta-oe \\
  ${MOUNT_TARGET}/yocto/meta-openembedded/meta-python \\
  ${MOUNT_TARGET}/yocto/meta-openembedded/meta-multimedia \\
  ${MOUNT_TARGET}/yocto/meta-openembedded/meta-networking \\
  ${MOUNT_TARGET}/yocto/meta-raspberrypi \\
  ${MOUNT_TARGET}/yocto/meta-qt5 \\
  ${MOUNT_TARGET}/yocto/meta-piracer \\
${EXTRA_BBLAYERS}
  \"
EOF

        if ! grep -q '# PiRacer Xen-Hypervisor config' conf/local.conf; then
            cat >> conf/local.conf <<EOF

# PiRacer Xen-Hypervisor config
MACHINE = \"raspberrypi4-64\"
BB_NUMBER_THREADS ?= \"8\"
PARALLEL_MAKE ?= \"-j8\"
LICENSE_FLAGS_ACCEPTED:append = \" synaptics-killswitch commercial\"
PACKAGECONFIG:append:pn-qtbase = \" eglfs linuxfb wayland\"
DISTRO_FEATURES:append = \" wayland opengl\"
PACKAGECONFIG:pn-qtwayland = \"wayland-client wayland-server wayland-egl\"
EXTRA_QMAKEVARS_PRE:pn-qtdeclarative-native = \"CONFIG+=no-jit\"
EXTRA_QMAKEVARS_PRE:pn-qtdeclarative = \"CONFIG+=no-jit\"
CFLAGS:append:pn-git-native = \" -std=gnu11\"
PACKAGECONFIG:remove:pn-qtbase = \"examples tests xcb xcb-gl\"
RPI_KERNEL_DEVICETREE_OVERLAYS:append = \" overlays/vc4-kms-dsi-waveshare-panel.dtbo overlays/mcp251xfd.dtbo\"
ENABLE_SPI_BUS = \"1\"
ENABLE_I2C = \"1\"
RPI_EXTRA_CONFIG = \"\
dtoverlay=vc4-kms-dsi-waveshare-panel,7_9_inch\n\
dtoverlay=mcp251xfd,spi0-0,interrupt=25\n\
dtparam=i2c_arm=on\n\
camera_auto_detect=0\n\
dtoverlay=imx219\n\
\"
IMAGE_INSTALL:append:pn-piracer-hu-image = \" qtmultimedia gstreamer1.0 gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly gstreamer1.0-libav v4l-utils ffmpeg libcamera libcamera-apps libcamera-gst\"
PACKAGECONFIG:append:pn-qtmultimedia = \" gstreamer\"
PACKAGECONFIG:append:pn-libcamera = \" gst\"
EOF
        fi

        if [ \"${ENABLE_XEN_CONFIG}\" = \"1\" ] && ! grep -q '# PiRacer Xen boot config' conf/local.conf; then
            cat >> conf/local.conf <<EOF

# PiRacer Xen boot config
DISTRO_FEATURES:append = \" xen virtualization\"
EOF
        fi

        if [ \"${ENABLE_XEN_CONFIG}\" = \"1\" ]; then
            sed -i '/xen-raspberrypi4-64.inc/d' conf/local.conf
        fi

        sed -i 's/^MACHINE ??= \"raspberrypi4-64\"/MACHINE = \"raspberrypi4-64\"/' conf/local.conf

        # BB_NUMBER_THREADS 환경 변수로 재정의 가능
        if [ -n \"\$BB_NUMBER_THREADS\" ]; then
            export BB_NUMBER_THREADS
            echo \"[Docker] BB_NUMBER_THREADS=\${BB_NUMBER_THREADS}\"
        fi

        echo '[Docker] BitBake 시작: ${TARGET}'
        bitbake ${BITBAKE_EXTRA_ARGS:-} ${TARGET}
        echo '[Docker] 빌드 완료!'
    "

# ── 빌드 결과 확인 ───────────────────────────────────────────────────────────
DEPLOY_DIR="${BUILD_DIR}/tmp/deploy/images/raspberrypi4-64"
if [ -d "${DEPLOY_DIR}" ]; then
    log_ok "빌드 완료! 이미지 파일:"
    ls -lh "${DEPLOY_DIR}"/*.wic* 2>/dev/null || \
    ls -lh "${DEPLOY_DIR}"/*.rootfs.* 2>/dev/null || \
    ls -lh "${DEPLOY_DIR}"/ | head -20
    echo ""
    log_ok "SD 카드 플래시: ./flash.sh <SD카드 장치>"
    log_ok "예시: ./flash.sh /dev/sdb"
else
    log_warn "deploy 디렉토리를 찾을 수 없습니다: ${DEPLOY_DIR}"
fi
